enum TextureFormat {
    TEXTUREFORMAT_UNSIGNED_BYTE,
    TEXTUREFORMAT_UNSIGNED_SHORT,
    TEXTUREFORMAT_UNSIGNED_INT,
    TEXTUREFORMAT_BYTE,
    TEXTUREFORMAT_SHORT,
    TEXTUREFORMAT_INT,
    TEXTUREFORMAT_FLOAT,
    TEXTUREFORMAT_HALF_FLOAT
}

export default TextureFormat;